Email and PAN addition in ECREQ as optional parameter
Sahamati/aa-redirection-guidelines pull request #17
Opened 2023-02-06 09:41 UTC by Athira-Jayakumar1

Email and PAN addition in ECREQ as optional parameter

2023-03-03 10:52 UTC, Athira-Jayakumar1 commented
@dheerajkhardwal @TeamSahamati Please review and approve

2023-03-18 11:03 UTC, dheerajkhardwal commented
Marking this to be released as `v1.3.0`

2023-03-18 11:03 UTC, dheerajkhardwal approved these changes

2023-03-18 11:09 UTC, dheerajkhardwal requested changes

2023-03-18 11:09 UTC, dheerajkhardwal commented on specification/request-specification.md
> +| emailid            | String              | Optional, can be blank. If FIU wants to notifiy the consent creation and subsequent notifications to the citizen thorugh email
Small typo in the description text: `thorugh`, please update.
Also, shall we keep the field name as just `email`?

2023-03-18 11:09 UTC, dheerajkhardwal commented on specification/request-specification.md
> +| PAN              | String              | Optional, can be blank. PAN of the citizen for discovery of certain FI categories like Mutual Funds
In order to keep the field naming consistent, let's use lowercase for this field name as well.

2023-03-20 07:25 UTC, Athira-Jayakumar1 commented
@dheerajkhardwal updated, Please check

2023-03-25 15:20 UTC, dheerajkhardwal approved these changes

2023-03-25 15:21 UTC, dheerajkhardwal commented
Thanks @Athira-Jayakumar1.

2023-03-25 15:21 UTC, merged